### ISSUE TITLE
clarify core workflows to cover

### ISSUE THREAD

**Issue by tomkralidis** [geopython/geopython-workshop#1]
List out core workflows we want to accomplish, based on workshop abstract:

`
With a low barrier to entry and large ecosystem of tools and libraries, Python is the lingua franca for geospatial development. Whether you are doing data acquisition, processing, publishing, integration or analysis, there are no shortage of solid Python tools to assist in your day to day workflows. This workshop will provide an introduction to performing common GIS/geospatial tasks using Python geospatial tools such as OWSLib, Shapely, Fiona/Rasterio, using common geospatial libraries like GDAL, PROJ, pycsw, and other tools from the geopython toolchain. Manipulate vector/raster data using Shapely, Fiona/Rasterio. Publish data and metadata to OGC web services using MapScript, pygeometa, and pycsw. Visualize your data on a map using Jupyter and Folium. Plus a few extras in between! The workshop is provided using the Jupyter Notebook environment with Python 3.
`

**Comment by tomkralidis** [comment]
Initial brainstorm:

- connect to OGC services (OWSLib)
- publishing metadata (pycsw)
- exposing processes (PyWPS)
- raster workflows (rasterio)
- vector workflows (fiona)
- emerging tools (pygeoapi)

**Comment by tomkralidis** [comment]
Will also have:

- introduction
- emerging technology/trends
- conclusion

**Comment by ldesousa** [comment]
Two other libraries I use quite a bit:
- Fiona
- geographiclib
And an emerging library:
- [pydggrid](https://github.com/am2222/pydggrid)

However, for a 4 hour workshop this might be a bit too much.

**Comment by justb4** [comment]
Now that I think of: I use Stetl https://stetl.org , Spatial ETL, a GeoPython project, a lot.

**Comment by tomkralidis** [comment]
Created in 9def24356f57d6d9bc0e1fe24dba7131fc68d13b
