### ISSUE TITLE
clarify existing branches

### ISSUE THREAD

**Issue by tomkralidis** [geopython/geopython-workshop#114]
The following branches require review/status update:
- `fixes-85-86-justs` (@justb4)
- `updates_by_krishna` (@krishnaglodha)

**Comment by justb4** [comment]
* `fixes-85-86-justs` was already merged, so deleted.

**Comment by krishnaglodha** [comment]
@tomkralidis I think we can remove `updates_by_krishna` as we have made changes to similar places
