### ISSUE TITLE
review section 06 - Data analysis

### ISSUE THREAD

**Issue by tomkralidis** [geopython/geopython-workshop#12]

**Comment by justb4** [comment]
### Show dates in x-axis

![image](https://user-images.githubusercontent.com/582630/63519740-c30cbe00-c4f3-11e9-8029-8209eb03f80d.png)

* solution: add `x_axis_type='datetime'` as in `p = figure(title='Bucharest 226 dobson', x_axis_label='foo', y_axis_label='Dobson units', x_axis_type='datetime')` see: [here](https://stackoverflow.com/questions/33869292/how-can-i-set-the-x-axis-as-datetimes-on-a-bokeh-plot)

### Where is the Analysis?

I don't see a real Analysis in selecting stations for WMO region VI. This is merely filtering GeoJSON data by attribute or am I overlooking something?  (Ok a lot of spatial analysis is merely querying and could be solved with just PostGIS).

### Missing: Raster Analysis

Probably too late in the game now and for next workshop version: I thought we would have a Raster Analysis case as well (thought the WOUDC case was raster-based).

**Comment by tomkralidis** [comment]
Thanks @justb4 

- added x axis fix (thanks!)
- the analysis here is via visualization support evaluation
- there's no raster data per se from WOUDC, but we can add something over time from other activities
