### ISSUE TITLE
Remove pygeoapi and pycsw from docker-compose

### ISSUE THREAD

**Issue by justb4** [geopython/geopython-workshop#120]
As it was decided starting FOSS4G 2023 to skip the Publication chapter, we won't need `pycsw` and `pygeoapi` in the [docker-compose.yml](https://github.com/geopython/geopython-workshop/blob/master/workshop/docker-compose.yml).

* saves enormous amount of startup time/bandwidth (about 1.5GB!)
* makes the local version equal to the Binder version of the WS

Unless we keep the 'Publication' chapter optional, then we may provide a dedicated `docker-compose.yml` for that.

**Comment by justb4** [comment]
oops I should have made it WIP - I am still working on the Notebook texts and to have all docker containers communicate...

**Comment by justb4** [comment]
will create new branch and PR and copy changes in there, just 4 files..

**Comment by francbartoli** [comment]
@justb4 your PR is merged now, feel free to close this

**Comment by justb4** [comment]
Ok, thanks @francbartoli ! Wanted to have this done upfront to have a leaner execution environment for anyone.

So:

* we can keep Section 9 (Publishing) but clearly make optional as in its starting text
* local pygeoapi Container access NB Cells moved from Section 10 to 9
* pygeoapi/pycsw services have dedicated docker-compose file
* but shares Docker Network with Jupyter WS Container and can be accessed from there
* hence when following Section 9, remote pygeoapi access works
