### ISSUE TITLE
proj warning

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/geopython-workshop#166]
![image](https://github.com/geopython/geopython-workshop/assets/299829/6cd87985-e585-4f03-b4b3-7e0e24357f62)

http://127.0.0.1:8888/notebooks/03-spatial-reference-systems.ipynb

is this problematic? should we warn the user about the warning?

**Comment by tomkralidis** [comment]
Good catch @pvgenuchten

@ldesousa should we update to `to_wkt()` for completeness? Other ideas?  Or do we want to explicitly demonstrate the issues of lossiness when using `to_proj4`?

**Comment by ldesousa** [comment]
That message is a good thing. I believe there was already something last year. Now it is more explicit.
