### ISSUE TITLE
buffer warning

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/geopython-workshop#167]
![image](https://github.com/geopython/geopython-workshop/assets/299829/e0234d84-3790-489f-bd86-57d0bb6cd2ee)

can we prevent the warning?

**Comment by tomkralidis** [comment]
Thanks @pvgenuchten.

@justb4 do we want to suppress warnings with `ogr.DontUseExceptions`, or do we want to keep to make a discussion point about GDAL/OGR warning handling?

**Comment by justb4** [comment]
Ok, this is a good educational point: think this comes from a more recent OGR than last workshop. When using OGR from Python it is good practice to enable Exceptions. This is what we do e.g. in the pygeoapi OGR Provider `init()`:

```
    # Exceptions will get raised on anything >= gdal.CE_Failure
    self.gdal.UseExceptions()
```

See https://pcjericks.github.io/py-gdalogr-cookbook/gdal_general.html#enable-python-exceptions. Will devote a couple of lines in Notebook.

**Comment by justb4** [comment]
(and prevent the warning).
