### ISSUE TITLE
update WxS to OGC APIs

### ISSUE THREAD

**Issue by tomkralidis** [geopython/geopython-workshop#181]
Update sections (i.e. Section) to prioritize OGC API workflows (keep WxS as secondary).  We could also add a paragraph / overview on OGC APIs.

**Comment by tomkralidis** [comment]
- @doublebyte1 added OGC API in https://github.com/geopython/geopython-workshop/pull/183
- @tomkralidis to do additional pass as needed

**Comment by doublebyte1** [comment]
@tomkralidis Please also check this one: https://github.com/geopython/geopython-workshop/pull/185
