### ISSUE TITLE
assign section delivery leads

### ISSUE THREAD

**Issue by tomkralidis** [geopython/geopython-workshop#31]
cc @francbartoli 

This issue identifies who is responsible for leading the delivery each section at FOSS4G 2019.  Of course is it implied that others provide support (questions, helping participants, prompting, etc.)

- [x] 1. Introduction: @tomkralidis 
- [x] 2. Geometry: @justb4 
- [x] 3. Spatial Reference Systems: @ldesousa  
- [x] 4. Vector data: @justb4 
- [x] 5. Raster data: @ldesousa 
- [x] 6. Data analysis: @kalxas 
- [x] 7. Visualization: @justb4 
- [x] 8. Metadata: @tomkralidis 
- [x] 9. Publishing: @kalxas 
- [x] 10. Remote data: @justb4 
- [x] 11. Emerging technology and trends: @tomkralidis  
- [x] 12. Conclusion: @tomkralidis

**Comment by tomkralidis** [comment]
@ldesousa thanks for signing up for 3 and 5, does this confirm you will now be at the workshop in person?

**Comment by ldesousa** [comment]
> @ldesousa thanks for signing up for 3 and 5, does this confirm you will now be at the workshop in person?

Sure!

**Comment by tomkralidis** [comment]
OK thanks.  Just checking given you mentioned previously that you would not be able to make it given a conflict on 26 August 2019.
