### ISSUE TITLE
Make sure that the workshop works for Windows users

### ISSUE THREAD

**Issue by justb4** [geopython/geopython-workshop#38]
## Problem
The workshop setup has not yet been tested on Windows. There may be all kinds of hurdles. This issue is to make sure that our setup is workable on Windows and probably add additional install notes, maybe even (`.cmd`) scripts.

Potential issues:
* bash and curl may not be available
* installing Docker for Windows (and Mac?) seems to require a Docker Store account
* setup depends on local disk Docker Volume mounts, will this work on Windows?
* Docker install is challenging, not even possible on Windows 10 Home Edition (?), see [MS Doc](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v)

## What to do
* have a Windows-user go through complete cycle: Docker and Docker Compose install, download .zip, run Docker, get Notebook URL and token etc.

## Solution notes
* Docker install, see this issue:  https://github.com/docker/docker.github.io/issues/6910
* there is a direct link to the Installer, thus no Docker Store required: https://download.docker.com/win/stable/Docker%20for%20Windows%20Installer.exe.

**Comment by justb4** [comment]
Interesting, I got a report from a user (translated from Dutch with Google T):

```
I cannot get the workshop started. Here are the steps I followed to get everything up and running.

1. Download Docker Desktop
The installer can be downloaded directly without having to log in via the URL https://download.docker.com/win/stable/Docker%20for%20Windows%20Installer.exe
2. Switching on Hyper-V
Open PowerShell with Admin rights
Run the following command:
Disable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-All
(This allows VirtualBox to run VM, this is more a comment and not important for the workshop)
Close the PowerShell
Press Windows button and type the following text:
Enable or disable Windows components
Go to 'Hyper-V' in the window and open everything
-> Turn on all check marks manually.
Please note, from now on VMs in VirtualBox no longer work.

Manually downloaded the master because osgeo4w curl cannot handle ssh (https://codeload.github.com/geopython/geopython-workshop/zip/master)
Open the zip file with the Explorer and then copy the content to the desired directory
cd geopython-workshop-master
cd workshop

Start:
docker compose up -d
After everything was first downloaded, I received the following error message:
==>
Creating geopython-workshop-pygeoapi ... error

ERROR: for geopython-workshop-jupyter Cannot create container for service jupyter: b'Drive has not been shared '
Creating geopython-workshop-pycsw ... error
ERROR: for geopython-workshop-pygeoapi Cannot create container for service pygeoapi: b'Drive has not been shared '

ERROR: for geopython-workshop-pycsw Cannot create container for service pycsw: b'Drive has not been shared '

ERROR: for jupyter Cannot create container for service jupyter: b'Drive has not been shared '

ERROR: for pygeoapi Cannot create container for service pygeoapi: b'Drive has not been shared '

ERROR: for pycsw Cannot create container for service pycsw: b'Drive has not been shared '
ERROR: Encountered errors while bringing up the project.

docker logs geopython-workshop-jupyter
==>
Error: No such container: geopython-workshop-jupyter
```

**Comment by tomkralidis** [comment]
As a workaround in this case I would suggest the downstream app pulls this out on their own with something like: https://stackoverflow.com/a/37409050

**Comment by justb4** [comment]
@tomkralidis above cmt belongs to OWSLib my guess...

**Comment by tomkralidis** [comment]
oops! pushing there.

**Comment by nickbearman** [comment]
Just to say, the setup on Windows (10 Pro) worked for me. 
I have been following this course: https://darribas.org/gds_course/content/home.html
And this setup (for Docker) was really helpful https://gdsl-ul.github.io/soft_install/

**Comment by nickbearman** [comment]
PS No Docker store account required for me.

**Comment by tomkralidis** [comment]
Thanks @nickbearman; added to docs.
