### ISSUE TITLE
review data

### ISSUE THREAD

**Issue by tomkralidis** [geopython/geopython-workshop#4]
Review data in current workshop and assess what to use or add/update.

from @kalxas: OSGeoLive will have an OSM output from Bucharest included in PostGIS and in Shapefiles.  @kalxas will clarify next week.

**Comment by tomkralidis** [comment]
Update: we agreed to go with [Natural Earth](https://www.naturalearthdata.com/) as the canonical dataset for the workshop.

**Comment by justb4** [comment]
+1 for NE. Next we can concentrate on which datasets/formats we need for the lessons, both vector and raster. There are e.g. interesting GIS analysis problems described like with [Highways+Protected Areas ](https://github.com/GISMentors/geopython-english/blob/master/workshop/01_vectors/05_highway_over_protected_areas.ipynb). We can recast to datasets with Countries & Rivers like "Through which countries flows river Donau?" and "What is the surface of Romania?" etc.
