### ISSUE TITLE
review FOSS4G 2021 workshop

### ISSUE THREAD

**Issue by tomkralidis** [geopython/geopython-workshop#41]
Perform an overall review of existing workshop:

- test run (does everything work as expected?)
- review workshop requirements/dependencies/versions
- section review
  - what to add/update/remove
  -  data updates?
- review existing [open issues](https://github.com/geopython/geopython-workshop/issues)

**Comment by tomkralidis** [comment]
As mentioned in https://github.com/geopython/geopython-workshop/issues/50#issuecomment-917621839, moving the discussion around relevant data here.

As mentioned by @justb4:
> "Localizing" the workshop content/data affects multiple chapters, plus the workshop may be provided at other events (maybe FOSS4G-NL Oct 2021) as well. And we are on a narrow timeframe with not too many human resources, who are busy...

Suggest we bring the entire workshop to a functional/working state (we are close), and then update the data to more more local to Argentina if we have time.

**Comment by tomkralidis** [comment]
cc @justb4 @ldesousa @francbartoli @kalxas @pvgenuchten

**Comment by justb4** [comment]
> > "Localizing" the workshop content/data affects multiple chapters, plus the workshop may be provided at other events (maybe FOSS4G-NL Oct 2021) as well. And we are on a narrow timeframe with not too many human resources, who are busy...
> 
> Suggest we bring the entire workshop to a functional/working state (we are close), and then update the data to more more local to Argentina if we have time.

+1

**Comment by francbartoli** [comment]
+1 @tomkralidis and @justb4

**Comment by ldesousa** [comment]
I support the idea of making the presentation more general and not directed at a particular location. But this is not so easy in section 3. I will reflect upon this a bit more before Friday.

**Comment by tomkralidis** [comment]
FYI for reference, some [FOSS4G 2021 relevant data/services](https://lists.osgeo.org/pipermail/osgeolive/2021-September/015509.html) being considered for OSGeoLive that we can consider if we decide to localize the workshop data

**Comment by tomkralidis** [comment]
In the soft topic/long debate category, for consistency we should do normalize how we format/print strings in our notebooks.  

Options:

1. `print('hello %s' % name)`
1. `print('hello {}'.format(name))`
1. `print(f'hello {name}')`
1. other options?

Thoughts?  +1 for option 3 from me for the workshop.

**Comment by francbartoli** [comment]
+1 for 3.

**Comment by tomkralidis** [comment]
Normalized in 1a7d2b08bd4cdf6196652d33c9eb9e7539fbfae2

**Comment by justb4** [comment]
+1 for 3, most modern option.

**Comment by kalxas** [comment]
+1 for 3

**Comment by tomkralidis** [comment]
Closing given we are good to go for tomorrow.
