### ISSUE TITLE
document workflow for Streamyard/Venueless

### ISSUE THREAD

**Issue by tomkralidis** [geopython/geopython-workshop#42]
The 2021 workshop delivery will be provided virtually/online via Streamyard for presenters (participants will use/see via Venueless).

Test/clarify/document (here) how the various presenters will be able to switch/present/share/etc. during the workshop.

**Comment by justb4** [comment]
Ok, will do.
I think it will be beneficial to use the Venueless "demo" instance for all presenters to meet and test.
The Venueless instance for the conference will be handed out only a week before. 
The URL to the demo instance is hidden, so I will provide via email. 

I briefly tested the Venueless Workshop demo instance (there is a Workshop 1 and Workshop 2). 
The setup/usage was quite straightforward, less challenging than the Talks that run via StreamYard. 
Technically the Workshop uses "Big Blue Button" internally I think. Video/Audio/Screen-sharing, e.g. using our Jupyter Notebook was easy, but we still should all get together at the same time there to get familiar. There is even more in there: shared whiteboard, polls and such, but we may not need all.

**Comment by tomkralidis** [comment]
Thanks @justb4.  FYI invite sent to all for rehearsal on 17 September 13h UTC.

**Comment by justb4** [comment]
Let's close this one and see at rehearsal. Like said Venueless/BigBlueButton is less challenging than StreamYard.
