### ISSUE TITLE
Workshop FOSS4G 2021 - Jupyter Notebook Chapter Owners

### ISSUE THREAD

**Issue by justb4** [geopython/geopython-workshop#43]
There are 12 Chapters in the Notebook. Works best if each one owns one or more Chapters
I start with the FOSS4G 2019 list, but add/remove yourself if you have no time, or are happy to take over a chapter when not listed at all (as Tom and I have quite some Chapters, I am happy to hand-over).

We can also track when a Chapter is "good to go".

- [x] 1. Introduction: @tomkralidis 
- [x] 2. Geometry: @justb4 
- [x] 3. Projections: @ldesousa 
- [x] 4. Vector data: @justb4 
- [x] 5. Raster data: @ldesousa 
- [x] 6. Data analysis: @francbartoli 
- [x] 7. Visualization: @justb4 
- [x] 8. Metadata: @tomkralidis 
- [x] 9. Publishing: @tomkralidis 
- [x] 10. Remote data: @justb4 
- [x] 11. Emerging technology and trends: @tomkralidis 
- [x] 12. Conclusion: @tomkralidis

**Comment by francbartoli** [comment]
Thanks @justb4, I've just assigned chapter 6 to myself. It was the only orphan

**Comment by tomkralidis** [comment]
Note: now that all sections are accounted for, I've opened issues foreach of them and have assigned to their owners.

I'm also happy to hand over sections for willing volunteers.

**Comment by tomkralidis** [comment]
Closing given we identified owners for all sections and now have distinct issues foreach section.
