### ISSUE TITLE
assign section content development

### ISSUE THREAD

**Issue by tomkralidis** [geopython/geopython-workshop#5]
- [x] 1. Introduction: @tomkralidis 
- [x] 2. Geometry: @justb4 
- [x] 3. Projections: @ldesousa 
- [x] 4. Vector data: @justb4 
- [x] 5. Raster data: @ldesousa 
- [x] 6. Data analysis: @justb4 / @tomkralidis
- [x] 7. Visualization: @justb4 
- [x] 8. Metadata: @tomkralidis 
- [x] 9. Publishing: @tomkralidis 
- [x] 10. Remote data: @justb4 
- [x] 11. Emerging technology and trends: @tomkralidis 
- [x] 12. Conclusion: @tomkralidis

**Comment by tomkralidis** [comment]
Update: we still need someone for section 6.

**Comment by kalxas** [comment]
I can help with content/testing after OSGeoLive release next week.
