### ISSUE TITLE
clarify whether .ipynb files should be saved with output cells cleared or not

### ISSUE THREAD

**Issue by tomkralidis** [geopython/geopython-workshop#60]
In 2019, we made sure that all code output cells were cleared when saving `.ipynb` files to version control.

We can keep the same approach for this year's delivery, which is beneficial for interactively running the notebooks during the workshop.  On the other hand, if we save the `.ipynb` files with cell outputs, this allows someone to view/follow right in GitHub for example (which renders Python notebooks).

No strong feelings either way from my perspective but interested to hear others' opinions here.

**Comment by justb4** [comment]
I prefer and always try to keep output cells cleared before commits. Note also that for each commit the Docker Image is rebuilt, thus with all cell outputs. 

My arguments in keeping cleared:

* the educational/surprise effect is better, I think there are even "poll/guess" type of Cells
* we still have the [Binder URL](https://mybinder.org/v2/gh/geopython/geopython-workshop/master?filepath=workshop%2Fjupyter%2Fcontent%2Fnotebooks%2F01-introduction.ipynb) for anyone who wants to browse

Maybe it is possible to automate filling all cells, saving it like a `gh-pages`,  making it a kind of browsable book? But still keep the original Cells/Notebooks all cleared.

**Comment by francbartoli** [comment]
+1 to keeping them cleared, thanks @justb4

**Comment by justb4** [comment]
I've added a [refresh-git.sh](https://github.com/geopython/geopython-workshop/blob/master/refresh-git.sh) Bash-script (forgot to mention this issue nr in commit) to the top dir. This will wipe all your local changes (but not new files) like when you have been testing the Notebooks and Cells are changed.  I use this script a lot., e.g. to try out new stuff quickly.

**Comment by tomkralidis** [comment]
thanks @justb4.  Let's keep them cleared as a rule.
