### ISSUE TITLE
Docker build in GitHub actions

### ISSUE THREAD

**Issue by justb4** [geopython/geopython-workshop#61]
Will be much faster, plus DockerHub is changing terms of use for free tiers.
See [this example](https://github.com/geopython/GeoHealthCheck/blob/master/.github/workflows/docker.yml) but can be more compact.

(Or were we as GH GeoPython accepted as Open Source org? @francbartoli I remember something or was that just `pygeoapi` ?)

Also: Action only needs to be triggered when the subdir `workshop/jupyter/*` is modified.

**Comment by justb4** [comment]
Ok, working in one go!

**Comment by francbartoli** [comment]
@justb4 we were accepted as an organization so for the whole set of projects

**Comment by justb4** [comment]
@francbartoli Ok, that is good!  Still the build/push via GH Action has advantages:

* much quicker (at least for now)
* triggered only when `workshop/jupyter/*` subdir-changes

**Comment by justb4** [comment]
Hmm, strictly spoken as the Notebooks are not in the Docker Image currently (but host-mounted in docker-compose.yml), the Docker build should not be triggered if Notebooks change. Will adapt the GH Workflow file.

**Comment by justb4** [comment]
Docker build ok, closing.
