### ISSUE TITLE
Communication with participants

### ISSUE THREAD

**Issue by justb4** [geopython/geopython-workshop#62]
We need to do communication with the participants, at least, fill in where needed:

- they are aware of the timezones and how to enter
- participants need to be aware they have to setup Docker on their system
- OR if they somehow cannot install Docker, can use the [Binder](https://mybinder.org/v2/gh/geopython/geopython-workshop/master?filepath=workshop%2Fjupyter%2Fcontent%2Fnotebooks%2F01-introduction.ipynb) as fallback, but need to be aware that it may suffer performance, startup time and more important will lack services (`pygeoapi, pycsw`) for the "Remote Data Chapter"
- comm channel, maybe [our Gitter](https://gitter.im/geopython/geopython-workshop) (hmm, maybe keep for development-only) or Telegram where they can ask questions.

**Comment by tomkralidis** [comment]
I've reached out to BALOC for advisory.  As in [2019](https://github.com/geopython/geopython-workshop/issues/21), we can use https://geopython.github.io/geopython-workshop as the entry point for participants.  Everything should be on that page to get users up and running.  Users should know when/where as part of the signing up for the workshop, and I imagine BALOC will provide connectivity info to them accordingly.  Will report back.

**Comment by tomkralidis** [comment]
BALOC recommended updating our entry as a means to communicate this information.

I've updated this at https://callforpapers.2021.foss4g.org/foss4g-2021-workshop/talk/7N3G3N/ (see Requirements for the Attendees).

BALOC will send an email to the attendees to let them know they should check their favorite talks and workshops for resources before the conference.
