### ISSUE TITLE
general feedback from FOSS4G2021 delivery

### ISSUE THREAD

**Issue by tomkralidis** [geopython/geopython-workshop#70]
General issue for gathering observations/feedback from our 2021 (virtual) delivery, to feed into FOSS4G 2022 delivery.

- 4 hours too short for the current workshop delivery; some sections rushed / could have benefited from more time.  Options:
  - consider a 2 part workshop?
  - consider profiling workshop for specific deliveries with less sections
  - other options?
- online delivery does not allow for circling the room to help participants
- add more exercises for students work on

Please feel free to add feedback/comments/ideas.

**Comment by justb4** [comment]
Yes I definitely would like to see students really do "work", i.e. exercises.

Thought hard how to split up, but found no ideal way: 

* Vector, Raster, Remote&Services, thus into three even, each with common Lessons.
* Beginner, Advanced
* Full Day no split.

I see usage beyond FOSS4G as well.
