### ISSUE TITLE
issue with running `visualisation`  code

### ISSUE THREAD

**Issue by krishnaglodha** [geopython/geopython-workshop#84]
I recently cloned repo and try to run the code. I'm getting error while running `fiona` package. 

<img width="783" alt="Screenshot 2022-08-07 at 8 26 23 PM" src="https://user-images.githubusercontent.com/47075664/183297188-00a69a24-cb3f-4c08-9b06-0981fb521546.png">

**Comment by krishnaglodha** [comment]
I'm guessing `numpy` error

**Comment by justb4** [comment]
Isn't this a duplicate of #80? Anyway my PR was merged somewhat later. Can you try the latest DockerHub version?

**Comment by krishnaglodha** [comment]
ok let me update docker
