### ISSUE TITLE
Test the MyBinder workshop version - fix lib-requirements if needed

### ISSUE THREAD

**Issue by justb4** [geopython/geopython-workshop#94]
This issue is  for just testing the MyBinder version and if needed update https://github.com/geopython/geopython-workshop/blob/master/binder/environment.yml where libs missing or versions not working. Everything except Remote Data should work.

Convenience link:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/geopython/geopython-workshop/master?filepath=workshop%2Fjupyter%2Fcontent%2Fnotebooks%2F01-introduction.ipynb)

**Comment by justb4** [comment]
I'll do chapters 1-4.

**Comment by ldesousa** [comment]
Chapter 4 is not working here with Binder. Apparently there is a kernel error, but I can't access the error messages.

**Comment by francbartoli** [comment]
@justb4 @ldesousa Binder is working completely now!

**Comment by justb4** [comment]
ok @francbartoli thanks, closing.
