### ISSUE TITLE
Facing issue on `pd.set_option('max_columns', 100)` in `vector-data` file

### ISSUE THREAD

**Issue by krishnaglodha** [geopython/geopython-workshop#96]
<img width="1120" alt="Screenshot 2022-08-19 at 08 31 07" src="https://user-images.githubusercontent.com/47075664/185557388-db58cbdc-c83b-4906-ac25-f60f78cb2419.png">

**Comment by justb4** [comment]
Maybe a local issue? Works with the Ch4 Notebook from PR #95 using the latest Docker Image (NOtebooks are not in the Docker Image but mounted in Docker Container) . 

Try to use the `./geopython-workshop-ctl.sh` to run the current workshop version in Docker.

![image](https://user-images.githubusercontent.com/582630/185607351-107d2f9e-c84f-4dd5-9531-8145f5c476f6.png)

**Comment by krishnaglodha** [comment]
I pushed the `display.max_columns` , earlier it was just `max_columns`
